### PR TITLE
Support incoming nodes with child nodes

### LINKED ISSUE #5: Doesn't recognise nested elements on added nodes
When a new node is added to the tree, if that node already has a subtree attached to it, the MutationObserver only has the root node in the `addedNodes` list, but `custom-attributes` doesn't check the subtree for any elements that have attributes in the registry.

Believe all that's needed is to call `_upgradeAttr` on any _added_ node i.e. in the `upgradeElement` function, with that element as the root, not the `ownerDocument`

### PR DESCRIPTION
**Pull request by bedeoverend**
Adds support for nodes being added to the tree which have their own child nodes.

Fixes #5

### CODE REVIEW

**Comment by bedeoverend** [comment]
Pretty small PR, but @matthewp would you mind having a quick look over, check it all looks fine? Cheers

**Review by matthewp — APPROVED** [review]
Looks good, thanks again!

**Comment by matthewp** [comment]
Going to release this as 1.0.1 b/c it's really a bug fix I think.

**Comment by matthewp** [comment]
Released 1.0.1

**Pull request merged**
