### PR TITLE
Includes all files in package.json

### PR DESCRIPTION
**Pull request by bedeoverend**
Adds new files introduced in 1.1.0 to package.json files property.

### CODE REVIEW

**Comment by bedeoverend** [comment]
@matthewp I installed latest with NPM and the files added in 1.1.0 were missing, I'm not hugely familiar with NPM, but I believe this should fix that?

**Comment by matthewp** [comment]
Right! Thanks, good catch.

**Comment by matthewp** [comment]
Released as 1.1.1

**Comment by bedeoverend** [comment]
@matthewp cheers! Could you do a 1.1.1 NPM release too? Ta

**Comment by matthewp** [comment]
I usually do that when I do the tag, forgot this time. Thanks! Published.

```
➜  custom-attributes git:(master) npm dist-tag ls custom-attributes
latest: 1.1.1
```

**Comment by bedeoverend** [comment]
Yeah no worries, figured - sorry for bugging. Looking good on my end, thanks :)

**Pull request merged**
